// client/src/lib/components/pos/Cart.svelte
<script lang="ts">
    import { cart, cartOperations } from "$lib/stores/pos.js";
    import { Button } from "$lib/components/ui/button/index.js";
    import {
        Card,
        CardContent,
        CardHeader,
        CardTitle,
    } from "$lib/components/ui/card/index.js";
    import { Input } from "$lib/components/ui/input/index.js";
    import { ScrollArea } from "$lib/components/ui/scroll-area/index.js";
    import { Separator } from "$lib/components/ui/separator/index.js";
    import {
        Table,
        TableBody,
        TableCell,
        TableHead,
        TableHeader,
        TableRow,
    } from "$lib/components/ui/table/index.js";
    import { Trash2, Plus, Minus } from "lucide-svelte";

    $: subtotal = $cart.reduce(
        (sum, item) => sum + item.product.price * item.quantity,
        0,
    );
    $: tax = subtotal * 0.08; // 8% tax
    $: total = subtotal + tax;

    function updateQuantity(productId: string, quantity: number) {
        cartOperations.updateQuantity(productId, quantity);
    }

    function removeItem(productId: string) {
        cartOperations.removeItem(productId);
    }

    function clearCart() {
        cartOperations.clear();
    }

    function formatPrice(price: number): string {
        return `$${price.toFixed(2)}`;
    }
</script>

<Card class="h-full flex flex-col">
    <CardHeader class="pb-4">
        <div class="flex items-center justify-between">
            <CardTitle class="text-lg">Current Order</CardTitle>
            {#if $cart.length > 0}
                <Button variant="outline" size="sm" onclick={clearCart}>
                    Clear All
                </Button>
            {/if}
        </div>
    </CardHeader>

    <CardContent class="flex-1 flex flex-col p-0">
        {#if $cart.length === 0}
            <div
                class="flex-1 flex items-center justify-center text-center p-8"
            >
                <div class="text-muted-foreground">
                    <p class="text-lg mb-2">Cart is empty</p>
                    <p class="text-sm">Add items from the product grid</p>
                </div>
            </div>
        {:else}
            <ScrollArea class="flex-1 px-6">
                <Table>
                    <TableHeader>
                        <TableRow>
                            <TableHead>Item</TableHead>
                            <TableHead class="text-center">Qty</TableHead>
                            <TableHead class="text-right">Price</TableHead>
                            <TableHead class="w-12"></TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {#each $cart as item (item.product.id)}
                            <TableRow>
                                <TableCell class="font-medium">
                                    <div>
                                        <p class="font-semibold">
                                            {item.product.name}
                                        </p>
                                        <p
                                            class="text-sm text-muted-foreground"
                                        >
                                            {formatPrice(item.product.price)} each
                                        </p>
                                    </div>
                                </TableCell>
                                <TableCell class="text-center">
                                    <div
                                        class="flex items-center justify-center gap-2"
                                    >
                                        <Button
                                            variant="outline"
                                            size="sm"
                                            class="h-6 w-6 p-0"
                                            onclick={() =>
                                                updateQuantity(
                                                    item.product.id,
                                                    item.quantity - 1,
                                                )}
                                        >
                                            <Minus class="h-3 w-3" />
                                        </Button>
                                        <Input
                                            type="number"
                                            min="1"
                                            value={item.quantity}
                                            oninput={(e) =>
                                                updateQuantity(
                                                    item.product.id,
                                                    parseInt(
                                                        e.currentTarget.value,
                                                    ) || 1,
                                                )}
                                            class="w-16 h-6 text-center text-xs"
                                        />
                                        <Button
                                            variant="outline"
                                            size="sm"
                                            class="h-6 w-6 p-0"
                                            onclick={() =>
                                                updateQuantity(
                                                    item.product.id,
                                                    item.quantity + 1,
                                                )}
                                        >
                                            <Plus class="h-3 w-3" />
                                        </Button>
                                    </div>
                                </TableCell>
                                <TableCell class="text-right font-semibold">
                                    {formatPrice(
                                        item.product.price * item.quantity,
                                    )}
                                </TableCell>
                                <TableCell>
                                    <Button
                                        variant="ghost"
                                        size="sm"
                                        class="h-6 w-6 p-0 text-destructive hover:text-destructive"
                                        onclick={() =>
                                            removeItem(item.product.id)}
                                    >
                                        <Trash2 class="h-3 w-3" />
                                    </Button>
                                </TableCell>
                            </TableRow>
                        {/each}
                    </TableBody>
                </Table>
            </ScrollArea>

            <div class="border-t p-6">
                <div class="space-y-2">
                    <div class="flex justify-between text-sm">
                        <span>Subtotal:</span>
                        <span>{formatPrice(subtotal)}</span>
                    </div>
                    <div class="flex justify-between text-sm">
                        <span>Tax (8%):</span>
                        <span>{formatPrice(tax)}</span>
                    </div>
                    <Separator />
                    <div class="flex justify-between text-lg font-bold">
                        <span>Total:</span>
                        <span>{formatPrice(total)}</span>
                    </div>
                </div>
            </div>
        {/if}
    </CardContent>
</Card>

// react/src/apps/pos/components/cart/Cart.tsx
import React from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { ScrollArea } from '@/components/ui/scroll-area';
import {
    Table,
    TableBody,
    TableHead,
    TableHeader,
    TableRow,
} from '@/components/ui/table';
import { useCart } from '../../hooks/use-pos';
import { EmptyCartMessage, CartItemRow, CartSummary } from './';

interface CartProps {
    /** CSS class name for styling */
    className?: string;
    /** Function to call when checkout is initiated */
    onCheckout?: () => void;
}

/**
 * Cart Component
 * 
 * Displays current cart items with quantity controls and pricing breakdown.
 * Allows users to modify quantities, remove items, and clear the entire cart.
 * 
 * @param props - Component props
 * @returns Cart component
 */
export function Cart({ className, onCheckout }: CartProps) {
    const {
        cart,
        subtotal,
        tax,
        total,
        formattedSubtotal,
        formattedTax,
        formattedTotal,
        isEmpty,
        updateCartQuantity,
        removeFromCart,
        clearCart,
    } = useCart();

    /**
     * Handle quantity input change
     */
    const handleQuantityChange = (productId: string, value: string) => {
        const quantity = parseInt(value) || 1;
        if (quantity > 0) {
            updateCartQuantity(productId, quantity);
        }
    };

    /**
     * Handle quantity increment
     */
    const handleIncrement = (productId: string, currentQuantity: number) => {
        updateCartQuantity(productId, currentQuantity + 1);
    };

    /**
     * Handle quantity decrement
     */
    const handleDecrement = (productId: string, currentQuantity: number) => {
        if (currentQuantity > 1) {
            updateCartQuantity(productId, currentQuantity - 1);
        } else {
            removeFromCart(productId);
        }
    };

    /**
     * Handle item removal
     */
    const handleRemoveItem = (productId: string) => {
        removeFromCart(productId);
    };

    /**
     * Handle clear cart
     */
    const handleClearCart = () => {
        if (window.confirm('Are you sure you want to clear the cart?')) {
            clearCart();
        }
    };

    return (
        <Card className={`h-full flex flex-col ${className}`}>
            <CardHeader className="pb-4">
                <div className="flex items-center justify-between">
                    <CardTitle className="text-lg">Current Order</CardTitle>
                    {!isEmpty && (
                        <Button
                            variant="outline"
                            size="sm"
                            onClick={handleClearCart}
                            aria-label="Clear all items from cart"
                        >
                            Clear All
                        </Button>
                    )}
                </div>
            </CardHeader>

            <CardContent className="flex-1 flex flex-col p-0">
                {isEmpty ? (
                    <EmptyCartMessage />
                ) : (
                    <>
                        {/* Cart Items */}
                        <ScrollArea className="flex-1 px-6">
                            <Table>
                                <TableHeader>
                                    <TableRow>
                                        <TableHead>Item</TableHead>
                                        <TableHead className="text-center">Qty</TableHead>
                                        <TableHead className="text-right">Price</TableHead>
                                        <TableHead className="w-12"></TableHead>
                                    </TableRow>
                                </TableHeader>
                                <TableBody>
                                    {cart.map((item) => (
                                        <CartItemRow
                                            key={item.product.id}
                                            item={item}
                                            onQuantityChange={handleQuantityChange}
                                            onIncrement={handleIncrement}
                                            onDecrement={handleDecrement}
                                            onRemove={handleRemoveItem}
                                        />
                                    ))}
                                </TableBody>
                            </Table>
                        </ScrollArea>

                        {/* Cart Summary */}
                        <CartSummary
                            subtotal={formattedSubtotal}
                            tax={formattedTax}
                            total={formattedTotal}
                            onCheckout={onCheckout}
                            isEmpty={isEmpty}
                        />
                    </>
                )}
            </CardContent>
        </Card>
    );
}

export default Cart;
