// vue/src/components/ui/datePicker/index.vue
<script setup lang="ts">
import type { DateValue } from "@internationalized/date";
import { DateFormatter, getLocalTimeZone } from "@internationalized/date";
import { Calendar as CalendarIcon } from "lucide-vue-next";

import { ref } from "vue";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Calendar } from "@/components/ui/calendar";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";

const df = new DateFormatter("en-US", {
  dateStyle: "long",
});

const value = ref<DateValue>();
</script>

<template>
  <Popover>
    <PopoverTrigger as-child>
      <Button
        variant="outline"
        :class="
          cn('w-[280px] justify-start text-left font-normal', !value && 'text-muted-foreground')
        "
      >
        <CalendarIcon class="mr-2 h-4 w-4" />
        {{ value ? df.format(value.toDate(getLocalTimeZone())) : "Pick a date" }}
      </Button>
    </PopoverTrigger>
    <PopoverContent class="w-auto p-0">
      <Calendar v-model="value" initial-focus />
    </PopoverContent>
  </Popover>
</template>

// client/src/lib/components/ui/date-picker/date-picker.svelte
<script lang="ts">
    import CalendarIcon from "@lucide/svelte/icons/calendar";
    import {
        type DateValue,
        DateFormatter,
        getLocalTimeZone,
    } from "@internationalized/date";
    import { cn } from "$lib/utils.js";
    import {
        Button,
        type ButtonProps,
    } from "$lib/components/ui/button/index.js";
    import { Calendar } from "$lib/components/ui/calendar/index.js";
    import * as Popover from "$lib/components/ui/popover/index.js";

    const df = new DateFormatter("en-US", {
        dateStyle: "long",
    });

    let value = $state<DateValue>();
</script>

<Popover.Root>
    <Popover.Trigger>
        {#snippet child({ props }: { props: ButtonProps })}
            <Button
                variant="outline"
                class={cn(
                    "w-[280px] justify-start text-left font-normal",
                    !value && "text-muted-foreground",
                )}
                {...props}
            >
                <CalendarIcon class="mr-2 size-4" />
                {value
                    ? df.format(value.toDate(getLocalTimeZone()))
                    : "Select a date"}
            </Button>
        {/snippet}
    </Popover.Trigger>
    <Popover.Content class="w-auto p-0">
        <Calendar bind:value type="single" initialFocus />
    </Popover.Content>
</Popover.Root>
